version: '3'
services:
  dns:
    restart: always
    image: cytopia/bind
    ports:
      - "53:53"
      - "53:53/udp"
    environment:
      - WILDCARD_DNS=home.gouws.com=192.168.1.10
      - DNS_FORWARDER=8.8.8.8,8.8.4.4

